litellm_settings:     # <--- Sahi block name yahan hai! 🎯
  drop_params: true   # <--- Yeh ab saari models par parameters ko drop karega
  model_prices_and_context_window_path: "/app/model_prices.json"